### ISSUE TITLE
Excessive DerivedData Warnings v3.3.0 and v3.2.0 for GBJailbreakDetection

### ISSUE THREAD

**Issue by kyleturner** [lmirosevic/GBDeviceInfo#34]
Hello @lmirosevic,

We seem to be having some compile-time warnings due to some changes that were made for Bit support with GBJailbreakDetection. I've tried DerivedData clean, Xcode clean, completely fresh pod install, etc. and am still not having any luck. My issues:

```objc
warning: object file (/Users/kyleturner/Projects/NeXgen-iOS/Pods/GBJailbreakDetection/GBJailbreakDetection.framework/GBJailbreakDetection(GBJailbreakDetection.o)) was built for newer iOS version (8.2) than being linked (8.0)
```

And about 10 instances of warnings like:

```objc
warning: /Users/lm/Library/Developer/Xcode/DerivedData/ModuleCache/2MGDRTGQWFKA4/Darwin-38I6DLZ5IH61J.pcm: No such file or directory
warning: /Users/lm/Library/Developer/Xcode/DerivedData/ModuleCache/2MGDRTGQWFKA4/ObjectiveC-1RQA2RIXJIE19.pcm: No such file or directory
```

or 

```objc
warning: Could not resolve external type c:objc(cs)NSArray
warning: Could not resolve external type c:objc(cs)NSString
warning: Could not resolve external type c:objc(cs)NSMethodSignature
```

Were local files accidentally included in your most recent Pod update?

We're pulling in `GBJailbreakDetection v1.1.0` with either version of `GBDeviceInfo` (3.3.0 or 3.2.0), but I'm not certain that was your intention? Maybe we're missing something on our end?

If you could please help us resolve this issue, that would be greatly appreciated. Please let us know if we can provide any more debugging information/repro steps.

Thank you!

**Comment by lmirosevic** [comment]
Hi @kyleturner I accidentally built the library with the min deployment target set to iOS 8.2. Presumably your min deployment target of your project is 7.0 so this why you are seeing this. 

I've recompiled the GBJailbreakDetection library (now at version `1.1.1`), with the min deployment target set to iOS 6.0. I've also released an update to GBDeviceInfo to match the min version (previously it was iOS 5.0 which is no longer supported as of the new jailbreak features). So please try a `pod update` and make sure that GBJailbreakDetection is at `1.1.1` and GBDeviceInfo at `3.4.0`.

**Comment by kyleturner** [comment]
Hey, thank you so much for the quick reply, glad it wasn't something crazy
on our end and glad we were able to help you resolve the issue! :)

Out for lunch but will check everything once I get back and let you know we
have everything resolved.

**Comment by kyleturner** [comment]
Hey @lmirosevic - quick update. Your new version seemed to have fixed the incompatibility update for deployment targets. However, I'm still seeing the errors about the (probably unexpected) missing files, specifically:

```objc
while processing /Users/kyleturner/Projects/NeXgen-iOS/Pods/GBJailbreakDetection/GBJailbreakDetection.framework/GBJailbreakDetection(GBJailbreakDetection.o):
warning: /Users/lm/Library/Developer/Xcode/DerivedData/ModuleCache/1UIOVPNM0I1EA/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
while processing /Users/kyleturner/Projects/NeXgen-iOS/Pods/GBJailbreakDetection/GBJailbreakDetection.framework/GBJailbreakDetection(GBJailbreakDetection.o):
warning: /Users/lm/Library/Developer/Xcode/DerivedData/ModuleCache/1UIOVPNM0I1EA/Foundation-3DFYNEBRQSXST.pcm: No object file for requested architecture
while processing /Users/kyleturner/Projects/NeXgen-iOS/Pods/GBJailbreakDetection/GBJailbreakDetection.framework/GBJailbreakDetection(GBJailbreakDetection.o):
warning: /Users/lm/Library/Developer/Xcode/DerivedData/ModuleCache/1UIOVPNM0I1EA/UIKit-1V5UHAPTOD24G.pcm: No such file or directory
while processing /Users/kyleturner/Projects/NeXgen-iOS/Pods/GBJailbreakDetection/GBJailbreakDetection.framework/GBJailbreakDetection(GBJailbreakDetection.o):
warning: /Users/lm/Library/Developer/Xcode/DerivedData/ModuleCache/1UIOVPNM0I1EA/UIKit-1V5UHAPTOD24G.pcm: No object file for requested architecture
while processing /Users/kyleturner/Projects/NeXgen-iOS/Pods/GBJailbreakDetection/GBJailbreakDetection.framework/GBJailbreakDetection(GBJailbreakDetection.o):
warning: /Users/lm/Library/Developer/Xcode/DerivedData/ModuleCache/1UIOVPNM0I1EA/Darwin-38I6DLZ5IH61J.pcm: No such file or directory
while processing /Users/kyleturner/Projects/NeXgen-iOS/Pods/GBJailbreakDetection/GBJailbreakDetection.framework/GBJailbreakDetection(GBJailbreakDetection.o):
warning: /Users/lm/Library/Developer/Xcode/DerivedData/ModuleCache/1UIOVPNM0I1EA/Darwin-38I6DLZ5IH61J.pcm: No object file for requested architecture
while processing /Users/kyleturner/Projects/NeXgen-iOS/Pods/GBJailbreakDetection/GBJailbreakDetection.framework/GBJailbreakDetection(GBJailbreakDetection.o):
warning: /Users/lm/Library/Developer/Xcode/DerivedData/ModuleCache/1UIOVPNM0I1EA/ObjectiveC-1RQA2RIXJIE19.pcm: No such file or directory
while processing /Users/kyleturner/Projects/NeXgen-iOS/Pods/GBJailbreakDetection/GBJailbreakDetection.framework/GBJailbreakDetection(GBJailbreakDetection.o):
warning: /Users/lm/Library/Developer/Xcode/DerivedData/ModuleCache/1UIOVPNM0I1EA/ObjectiveC-1RQA2RIXJIE19.pcm: No object file for requested architecture
while processing /Users/kyleturner/Projects/NeXgen-iOS/Pods/GBJailbreakDetection/GBJailbreakDetection.framework/GBJailbreakDetection(GBJailbreakDetection.o):
warning: Could not resolve external type c:objc(cs)NSURL
while processing /Users/kyleturner/Projects/NeXgen-iOS/Pods/GBJailbreakDetection/GBJailbreakDetection.framework/GBJailbreakDetection(GBJailbreakDetection.o):
warning: Could not resolve external type c:objc(cs)NSFileManager
while processing /Users/kyleturner/Projects/NeXgen-iOS/Pods/GBJailbreakDetection/GBJailbreakDetection.framework/GBJailbreakDetection(GBJailbreakDetection.o):
warning: Could not resolve external type c:objc(cs)NSArray
while processing /Users/kyleturner/Projects/NeXgen-iOS/Pods/GBJailbreakDetection/GBJailbreakDetection.framework/GBJailbreakDetection(GBJailbreakDetection.o):
warning: Could not resolve external type c:objc(cs)NSString
while processing /Users/kyleturner/Projects/NeXgen-iOS/Pods/GBJailbreakDetection/GBJailbreakDetection.framework/GBJailbreakDetection(GBJailbreakDetection.o):
warning: Could not resolve external type c:@SA@regex_t
while processing /Users/kyleturner/Projects/NeXgen-iOS/Pods/GBJailbreakDetection/GBJailbreakDetection.framework/GBJailbreakDetection(GBJailbreakDetection.o):
warning: Could not resolve external type c:objc(cs)NSMethodSignature
while processing /Users/kyleturner/Projects/NeXgen-iOS/Pods/GBJailbreakDetection/GBJailbreakDetection.framework/GBJailbreakDetection(GBJailbreakDetection.o):
warning: Could not resolve external type c:objc(cs)NSMutableString
while processing /Users/kyleturner/Projects/NeXgen-iOS/Pods/GBJailbreakDetection/GBJailbreakDetection.framework/GBJailbreakDetection(GBJailbreakDetection.o):
warning: Could not resolve external type c:objc(cs)NSInvocation
```

Any ideas?

**Comment by kyleturner** [comment]
More accurately, these are the true warnings that are causing the above:

```objc
warning: /Users/lm/Library/Developer/Xcode/DerivedData/ModuleCache/1UIOVPNM0I1EA/Foundation-3DFYNEBRQSXST.pcm: No such file or directory

warning: /Users/lm/Library/Developer/Xcode/DerivedData/ModuleCache/1UIOVPNM0I1EA/Foundation-3DFYNEBRQSXST.pcm: No object file for requested architecture

warning: /Users/lm/Library/Developer/Xcode/DerivedData/ModuleCache/1UIOVPNM0I1EA/UIKit-1V5UHAPTOD24G.pcm: No such file or directory

warning: /Users/lm/Library/Developer/Xcode/DerivedData/ModuleCache/1UIOVPNM0I1EA/UIKit-1V5UHAPTOD24G.pcm: No object file for requested architecture

warning: /Users/lm/Library/Developer/Xcode/DerivedData/ModuleCache/1UIOVPNM0I1EA/Darwin-38I6DLZ5IH61J.pcm: No such file or directory

warning: /Users/lm/Library/Developer/Xcode/DerivedData/ModuleCache/1UIOVPNM0I1EA/Darwin-38I6DLZ5IH61J.pcm: No object file for requested architecture

warning: /Users/lm/Library/Developer/Xcode/DerivedData/ModuleCache/1UIOVPNM0I1EA/ObjectiveC-1RQA2RIXJIE19.pcm: No such file or directory

warning: /Users/lm/Library/Developer/Xcode/DerivedData/ModuleCache/1UIOVPNM0I1EA/ObjectiveC-1RQA2RIXJIE19.pcm: No object file for requested architecture

warning: Could not resolve external type c:objc(cs)NSURL
warning: Could not resolve external type c:objc(cs)NSFileManager
warning: Could not resolve external type c:objc(cs)NSArray
warning: Could not resolve external type c:objc(cs)NSString
warning: Could not resolve external type c:@SA@regex_t
warning: Could not resolve external type c:objc(cs)NSMethodSignature
warning: Could not resolve external type c:objc(cs)NSMutableString
warning: Could not resolve external type c:objc(cs)NSInvocation

```

**Comment by lmirosevic** [comment]
Should be fixed now with GBJailbreakDetection `1.2.0`

**Comment by kyleturner** [comment]
@lmirosevic we're in business! Thank you for making this a priority today. Issue resolved. :+1:
